FROM ubuntu:xenial

RUN apt-get update && apt-get install -y \
    sudo \
    bash-completion \
    emacs24-nox \
    git \
    python3 \
    python3-dev \
    make \
    r-base \
    vim \
    wget && \
ln -s /bin/python3 /bin/python && \
apt-get clean && rm -rf /var/lib/apt/lists/*

ARG user
ENV user ${user:-user}
RUN adduser --disabled-password --gecos "" --shell "/bin/bash" $user && \
    usermod -aG sudo $user && \
    echo "$user:docker" | chpasswd && \
    passwd -e $user


